dolthub/doltgresql

server/logrepl/replication.go, testing/ReplicationTestDockerfile, testing/replication-test-entrypoint.sh
Seeking some feedback on this approach. This works locally for me on my local Docker when I build the image from the package root:
```bash
docker build --file=testing/ReplicationTestDockerfile .
```
Next step would be to create a github action that runs this docker file and a workflow trigger for that action. Is this going to work? I looked into the examples in the Dolt repo and got confused by the paths that github actions appears to use at execution time, so could use some advice on best practices.
=> Docker test for postgres replication

.github/workflows/replication-tests.yaml
Test runner for docker-based replication tests
=> New test runner

server/types/array.go
This is building off of the following PR comment:
https://github.com/dolthub/doltgresql/pull/162#discussion_r1550630800
In Postgres, there seems to be a field size limit of 1GB, so I've used that to determine that we can just use `uint32`s everywhere, rather than having two formats with `uint16` and `uint64` (which were attempts at conserving space).
=> Reworked array serialization format

.github/workflows/cd-release.yaml
Reverts dolthub/doltgresql#176 as these actions have been updated and work now
=> Revert "/.github/workflows/cd-release.yaml: revert bump of dolthub actions"

server/ast/limit.go, testing/go/smoke_test.go
Fixes https://github.com/dolthub/doltgresql/issues/172
=> Fixes LIMIT

server/server.go
=> Release v0.7.0

server/server.go
=> Release v0.7.5

server/server.go
=> Release v0.8.0

server/server.go
=> Release v0.9.0

postgres/parser/sem/tree/function_definition.go, postgres/parser/sem/tree/function_name.go, postgres/parser/sem/tree/name_resolution.go, server/functions/current_catalog.go, server/functions/current_database.go, server/functions/current_schema.go, server/functions/framework/functions.go, server/functions/init.go, testing/go/functions_test.go
Will follow up with the corresponding table functions in another PR
=> Implement `current_schema`, `current_catalog` and `current_database` functions

server/ast/resolvable_type_reference.go, server/connection_handler.go
Also improved the error output when attempting to use geometry types
=> Fixed panic during handling of another panic

server/server.go
=> Release v0.10.0

go.mod, go.sum
\`\`\`
\$ go get github.com/dolthub/<dependency>/go@<commit>
\`\`\`
=> [auto-bump] [no-release-notes] dependency by nicktobey

server/server.go
=> Release v0.11.0

server/ast/aliased_table_expr.go, testing/go/pgcatalog_test.go, testing/go/subqueries_test.go
Fixes column resolution problems when using subqueries in joins.
Partially addresses https://github.com/dolthub/doltgresql/issues/554
=> More bug fixes for subqueries

server/server.go
=> Release v0.11.1

core/context.go, postgres/parser/parser/sql.y, postgres/parser/sem/tree/copy.go, server/ast/copy_from.go, server/node/copy_from.go, server/node/create_sequence.go, server/node/discard.go, testing/generation/command_docs/output/copy_test.go
This was pulled from:
* https://github.com/dolthub/doltgresql/pull/672
Separating the `COPY FROM` portion from the regression tests.
=> Added COPY FROM

go.mod, go.sum, testing/go/dolt_functions_test.go
Dolt PR: https://github.com/dolthub/dolt/pull/8381
=> Smoke tests for dolt diff functions/tables

go.mod, go.sum
=> [auto-bump] [no-release-notes] dependency by tbantle22

server/ast/alter_table.go, testing/go/alter_table_test.go
Helps with data imports, since it's common to add FKs at the end of an import script. 
The regression below seems to come from the FK being added, but we don't yet support removing an FK, so the `drop table` call now fails. 
Related to https://github.com/dolthub/doltgresql/issues/724
=> Add support for `ALTER TABLE ADD FOREIGN KEY` 

server/server.go
=> Release v0.12.0

README.md, go.mod, go.sum, testing/go/dolt_functions_test.go, testing/go/enginetest/doltgres_engine_test.go, testing/go/getting_started_guide_test.go, testing/go/schemas_test.go, testing/postgres-client-tests/node/workbenchTests/branches.js, testing/postgres-client-tests/node/workbenchTests/diffs.js, testing/postgres-client-tests/node/workbenchTests/schemas.js, testing/postgres-client-tests/node/workbenchTests/table.js
Dolt PR: https://github.com/dolthub/dolt/pull/8411
=> Fix diff functions, return `schema.table` for table_name columns

server/server.go
=> Release v0.13.0

server/ast/alter_table.go
We support multi alter statements, so we shouldn't error.
=> support multi-alter statements

server/server.go
=> Release v0.14.0

server/server.go
=> Release v0.14.1

.github/workflows/mini-sysbench.yml, .gitignore, scripts/quick_sysbench.sh, testing/go/benchmark/benchmark_folder.go, testing/go/benchmark/main.go, testing/go/benchmark/map.go, testing/go/benchmark/section.go, testing/go/regression/tool/main.go
This adds a new workflow that runs on every PR, similar to the regression tests. This runs a small version of the sysbench tests, primarily to detect large performance changes that a PR may unexpectedly introduce.
=> Added a mini sysbench test that runs on PRs

.github/workflows/mini-sysbench.yml
This is the review PR for the following new workflow:
* https://github.com/dolthub/doltgresql/pull/988
Due to how workflows are handled, the previous PR had to be merged into `main` before it could be debugged thoroughly. Therefore, this PR is for feedback! Below you'll also see what they look like.
=> [no-release-notes] Small benchmark workflow fix

server/server.go
=> Release v0.15.0

go.mod, go.sum
=> [auto-bump] [no-release-notes] dependency by jycor

go.mod, go.sum
=> [auto-bump] [no-release-notes] dependency by fulghum

go.mod, go.sum, postgres/parser/parser/sql.y, server/ast/alter_view.go, server/ast/column_table_def.go, server/ast/convert.go, server/ast/create_extension.go, server/doltgres_handler.go, server/functions/substr.go, testing/go/create_table_test.go, testing/go/functions_test.go, testing/go/trigger_test.go
Fixes a parser bug that disallowed calling a function with no arguments.
Implements a missing form of the substring() function.
Diff includes https://github.com/dolthub/doltgresql/pull/1154
=> Fixed several bugs related to column default expressions and generated columns

go.mod, go.sum
=> [auto-bump] [no-release-notes] dependency by reltuk

server/plpgsql/statements.go, testing/go/create_function_test.go
In function bodies, when replacing variable names with variable reference IDs, we were replacing any text matching the variable name, which wasn't always correct. This new approach tokenizes the expression and replaces only the tokens that exactly match a known variable name. There is still at least one more edge case we can fix in a follow up.
=> Bug fix: Function variable reference substitution

postgres/parser/types/types.go, server/ast/create_function.go, server/plpgsql/interpreter_logic.go, server/plpgsql/interpreter_operation.go, server/plpgsql/json.go, server/plpgsql/json_convert.go, server/plpgsql/parse.go, server/plpgsql/statements.go, testing/go/create_function_test.go
Hoped to get a few more statements in, but there's an issue where some statements that are ran from the interpreter are seemingly being discarded. It was a roadblock even for these two, hence the skipped tests. That's the next thing I'mma look into, as it's a pretty big issue (especially since there's no error, just no effect which is even worse).
=> Added SELECT ... INTO and PERFORM, plus bugfixes

server/server.go
=> [no-release-notes] Release v0.17.0

server/ast/create_function.go, server/plpgsql/json.go, server/plpgsql/json_convert.go, testing/go/create_function_test.go
Adds basic support for `WHILE` statements in PL/pgSQL. No support for labels yet.
=> `WHILE` statements in PL/pgSQL

go.mod, go.sum
=> [auto-bump] [no-release-notes] dependency by macneale4

server/server.go
=> [no-release-notes] Release v0.17.1

server/server.go
=> [no-release-notes] Release v0.18.0

go.mod, go.sum
=> [auto-bump] [no-release-notes] dependency by zachmu

postgres/parser/parser/sql.y, server/ast/create_database.go, testing/go/create_database_test.go, testing/go/create_table_test.go, testing/go/types_test.go
Also improved the error message for certain type errors.
=> Relaxed collation restrictions (reduced to warnings) in CREATE DATABASE

server/ast/constraint_table_def.go, testing/go/alter_table_test.go
Depends on: https://github.com/dolthub/go-mysql-server/pull/2936
Depends on: https://github.com/dolthub/vitess/pull/411
=> Add support for `ALTER TABLE ... DROP CONSTRAINT IF EXISTS`

server/server.go
=> [no-release-notes] Release v0.50.0

server/server.go
=> [no-release-notes] Release v0.50.1

testing/go/select_test.go
Confirmed fix for https://github.com/dolthub/doltgresql/issues/1424
=> Added test for VALUES() select statements interacting with prepared statements

core/context.go, core/id/registry.go, core/rootvalue.go, core/sequence_id.go, server/analyzer/assign_triggers.go, server/ast/show_create.go, server/ast/show_databases.go, server/ast/show_indexes.go, server/ast/show_schemas.go, server/ast/show_sequences.go, server/connection_handler.go, server/doltgres_handler.go, server/expression/in_subquery.go, server/functions/iterate.go, server/functions/nextval.go, server/functions/pg_get_serial_sequence.go, server/functions/setval.go, server/node/create_sequence.go, server/node/create_trigger.go, server/node/drop_sequence.go, server/node/drop_table.go, server/node/show_schemas.go, server/node/show_sequences.go, server/types/type.go, testing/go/create_function_test.go, testing/go/sequences_test.go, testing/go/show_tables_test.go, testing/go/show_test.go
One of the new tests for SHOW SEQUENCES exposes a very bad bug:
```
error running query: dangling ref: found dangling references to HashSet {
a084r0i9e18t0gq6m3s6qmp86pfq4hos
dq8tbqfe39u1hah2bs0ilg63rfk3vok2
}
```
I'm worried this is something pretty nasty in session / context management in doltgres.
=> Implemented support for various SHOW statements

server/ast/expr.go, server/ast/select.go, testing/go/pgcatalog_test.go
This fixes the failing query in https://github.com/dolthub/doltgresql/issues/1464
=> Bug fix for name resolution

server/functions/init.go, server/functions/pg_type_is_visible.go, server/tables/pgcatalog/pg_catalog_cache.go, server/tables/pgcatalog/pg_type.go, testing/go/functions_test.go, testing/go/pgcatalog_test.go
Also added user types to pg_types table
Partial fix for #1465
=> Implemented pg_type_is_visible

postgres/parser/parser/sql.y, testing/go/select_test.go
Resolves https://github.com/dolthub/doltgresql/issues/1470
=> Add support for `SELECT` statements with no expressions

server/server.go
=> [no-release-notes] Release v0.51.0

server/server.go
=> [no-release-notes] Release v0.51.1

testing/go/insert_test.go
Unskipping tests from https://github.com/dolthub/doltgresql/issues/1393
=> [no-release-notes] Unskipping tests that pass now

server/server.go
=> [no-release-notes] Release v0.52.2

server/server.go
Reverts dolthub/doltgresql#1914
=> Revert "[no-release-notes] Release v0.52.2"
