dolthub/doltgresql

server/ast/index_table_def.go
This is to bootstrap compatibility until we can implement descending order indexes. Since GMS assumes all indexes are ordered ascending, this will not impact correctness, just produce slightly different schemas.
=> Warn on non-ascending index

postgres/connection/connection.go, postgres/messages/row_description.go, server/implicit_commit.go, server/listener.go, testing/go/framework_test.go, testing/go/smoke_test.go, testing/go/ssl_test.go
This primarily implements four things:
1) We now discard all messages until we reach a `Sync` message when an error occurs, which is consistent with the [documentation](https://www.postgresql.org/docs/15/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY).
2) Proper support for boolean results. The `sqllogictests` make use of them, and GMS doesn't have a native boolean type, so we treat all booleans as `Int32` types. You can read more in the comments.
3) Proper error handling is the multi-message test case. Our `conn.Query` calls in tests only return specific kinds of errors, and all other errors are put into the returned `rows`. This differs from `conn.Exec`, which returns _all_ errors. Previously, we never checked for an error in `rows` (since I never knew an error would be put there), so it …
=> Fixed INT8 handling, support for testing statements, proper connection error handling

testing/generation/command_docs/create_tests.go, testing/generation/command_docs/generator_stack.go, testing/generation/command_docs/scanner.go, testing/generation/command_docs/statement_generator.go, testing/generation/command_docs/token.go, testing/generation/command_docs/token_reader.go
This adds the ability to count the number of permutations without having to actually loop through them all and increment one by one. This also adds variable declaration support (the `where VAR is one of:` in the synopsis). With those two, I can now verify that with _some_ of the variables defined in `SELECT`, we're up to **144 septillion** variations lol. I also removed the repetition strategy, which cut out a _ton_ of tests that probably weren't necessary (exponential on top of combinatorial).
This is a prelude to the next PR. I've found a strategy to be able to grab a deterministic set of tests (we can randomly decide the set, but given the proper input it's deterministic), but it requires knowing the number of possible permutations ahead of time, hence this PR.
=> Added permutation counting, variable definitions to parser test generation

testing/generation/command_docs/ints.go, testing/generation/command_docs/statement_generator.go
This allows you to pass in a number and get that exact permutation. So that means that, even though `SELECT` has 144 septillion permutations, if we give it `25,757,684,286,468,754`, then it will give us exactly that permutation. So to generate a set of tests, we just generate some amount of random numbers between _`[0, permutations)`_, and we have our tests!
=> Added the ability to get an exact permutation from parser tests

.github/workflows/cd-release.yaml
GH Actions cannot bypass branch rules, so this is an attempt to have them play by the same rules.
=> Potentially fix release workflow

testing/go/issues_test.go
https://github.com/dolthub/doltgresql/issues/25 was incorrect in its assumptions, but still proved valuable for learning. As a result, I've modified the skipped test so that we're now checking the same relative thing.
=> Correct issue test

.github/workflows/ci-staticcheck.yaml, CONTRIBUTING.md, README.md, main.go, scripts/run_staticcheck.sh, server/server.go, testing/bats/setup/common.bash, testing/bats/setup/query-server-common.bash, testing/bats/setup/windows-compat.bash
Previously, when running `doltgres`, it would look at the current directory to determine if it was a valid DoltgreSQL directory. If it wasn't, then it would attempt to create a `doltgres` database within the directory. This behavior was chosen since "it just works", which is a selling point of the product. This was causing issues though, as users would run the tool from within the same directory that they downloaded it in. This caused an error message to appear stating that the file was conflicting with the attempt to create the database, however users were still confused by the behavior even with the error message.
This default behavior has been changed. We now use the `~/doltgres/databases` directory as the default directory. It no longer matters where you run `doltgres` from, it will …
=> Changed default database creation behavior

server/server.go, testing/bats/doltgres.bats, testing/bats/psql-commands.bats, testing/bats/setup/common.bash, testing/bats/setup/query-server-common.bash
Currently, doltgres uses dolt init when starting doltgres server with data dir set to empty directory. When there is no dolt or doltgres config `user.name` and `user.email`, it fails to create a new database with error message from `dolt init`, which suggests to set `dolt` user info. Current fix will not return error; instead, it will use user name, `postgres` and email, `postgres@somewhere.com` if it's not set.
=> starting doltgres server creates db in defined directory

CONTRIBUTING.md, server/ast/expr.go, server/ast/resolvable_type_reference.go, server/functions/cbrt.go, server/functions/gcd.go, server/functions/lcm.go, server/functions/round.go, server/functions/zinternal_catalog.go, server/functions/zinternal_compiled_function.go, server/functions/zinternal_overload_deduction.go, server/functions/zinternal_parameters.go, server/functions/zinternal_source.go, server/listener.go, testing/go/functions_test.go, utils/abs.go
This is the 2nd version of my attempt at implementing functions.
The first iteration hijacked `*tree.FuncExpr` and special-cased names of functions that matched the built-in ones for Postgres. Then it returned a new node that approximated the functionality. In some cases this was as simple as returning a different `*vitess.FuncExpr` node that pointed to a different function, however some cases did not have direct analogues in MySQL. Originally I was going to ignore those, but since I was working on functions anyway, I decided to tackle them to get it over with, similar to my approach with the [entire AST conversion](https://github.com/dolthub/doltgresql/pull/49). Well that's when I started running into two key issues:
1) No straightforward conversion for some functions
2) Different …
=> Added a framework for creating PostgreSQL functions

postgres/parser/uuid/codec.go, server/ast/resolvable_type_reference.go, server/types/serialization.go, server/types/uuid.go, testing/go/types_test.go
This adds the UUID type. Ignore the serialization portion for now, I'll figure out a different serialization scheme later that should work for all types (including user-defined types). While this _works_, we need to forward the type information through to the connector so it can use the correct OID. For now though, this should be enough to unblock.
=> Added UUID type

postgres/parser/parser/parse.go, postgres/parser/parser/sql.y, server/ast/order_by.go, testing/go/types_test.go
There are two bugs here. The first is that `INTEGER` and `INT` were parsing as `INT8`. The second is that `ORDER BY 1` was failing for tables that had an `INT4` but not an `INT8`. For the first, our parser simply used the wrong bit width, which is fairly straightforward.
The second bug was _far_ trickier to track down. Essentially, `ORDER BY 1` has been broken, however some combinations of tables and rows would result in the correct order _on accident_, and that's what led to the confusion on how the second bug worked. It's even more coincidental that the literal `1` in `ORDER BY 1` happened to correspond to the first value in the affected tests, further masking the issue.
Fundamentally, the issue has not been **fixed**, and this submits a workaround. The root of the issue is that GMS …
=> INT4 ORDER BY Workaround

.github/workflows/cd-release.yaml
The parser needs to be built before `go run -mod=readonly ./utils/genminver_validation/ $FILE`
=> build parser earlier in release process

.github/workflows/cd-release.yaml
Does the same thing as: https://github.com/dolthub/dolt/blob/main/.github/workflows/cd-release-pgo.yaml#L79
=> add the minver_validation.txt file to the release commit

postgres/messages/command_complete.go, server/connection_handler.go
This PR fixes issue connecting to doltgres server using Postgres JDBC driver.
In [Postgres docs](https://www.postgresql.org/docs/current/protocol-flow.html), it says, "`Execute` doesn't cause ReadyForQuery or RowDescription to be issued."
Also, queries that don't return set of rows send `NoData` in response to `Describe` message.
=> `EXECUTE` doesn't send RowDescription

postgres/parser/parser/parse.go, postgres/parser/types/types.go, server/expression/explicit_cast.go, server/functions/framework/compiled_function.go, server/types/array.go, server/types/bool_array.go, server/types/char.go, server/types/char_array.go, server/types/name_array.go, server/types/text_array.go, server/types/varchar.go, server/types/varchar_array.go, testing/go/operators_test.go, testing/go/smoke_test.go, testing/go/types_test.go
This adds functionality so that string literals such as `'{1,2,3}'` can be interpreted as arrays of _any_ type. This builds off of the https://github.com/dolthub/doltgresql/pull/333 PR, which enables this to "just work" for all contexts (includes casting, inserting into columns, automatic operator resolution, etc.). This also includes additional tests for a few bugs that weren't caught in the previous PR.
=> Added string literal to array interpretation

cmd/doltgres/main.go, go.mod, go.sum, server/server.go, servercfg/config.go, testing/bats/doltgres.bats
This change reworks how the data dir, config file and related initialization values are loaded. The main effect is that it's now possible to run `doltgres` without a config.yaml file.
The sever config is now resolved in this order
1. --config flag
2. config.yaml file if present
3. Built-in default config values
The data-dir for this config is then overridden as necessary with a similar pattern:
1. --data-dir flag
2. The value in a config.yaml file if, if a file was loaded
3. The env var `DOLTGRES_DATA_DIR`
4. The default ($home/doltgres/databases)
=> Reworked config

server/listener.go
Fixes https://github.com/dolthub/doltgresql/issues/348
Idle connections were timing out in 60s before this change.
=> Added correct timeouts to server

server/functions/framework/catalog.go, server/functions/framework/compiled_function.go, server/functions/framework/intermediate_function.go
Functions did their entire overload resolution during `Eval`, meaning if a function was called 1000 times, then we did overload resolution 1000 times for the exact same function. This changes it so that we only do it once. This optimization was made while investigating our performance benchmarks.
Of note, errors found during overload resolution are stashed for later. This ensures that other steps in the pipeline retain their error priority. Previously, when this was all done in `Eval`, stashing wasn't needed.
=> Perform function analysis once

cmd/doltgres/main.go, go.mod, go.sum, server/connection_handler.go, testing/bats/psql-commands.bats, utils/pprof.go
This changes the hardcoded PSQL statements that were no longer working so that they now work. In addition, I'm including the `pprof` additions here, as I added this for sysbench testing. I more-or-less copied the implementation from Dolt. I think we used to have it in Doltgres, but removed it when we removed the `sql-server` command.
=> Reworked PSQL statements

server/tables/pgcatalog/init.go, server/tables/pgcatalog/pg_am.go, server/tables/pgcatalog/pg_attribute.go, server/tables/pgcatalog/pg_class.go, server/tables/pgcatalog/pg_constraint.go, server/tables/pgcatalog/pg_event_trigger.go, server/tables/pgcatalog/pg_index.go, server/tables/pgcatalog/pg_namespace.go, server/tables/pgcatalog/pg_proc.go, server/tables/pgcatalog/pg_trigger.go, server/tables/pgcatalog/pg_type.go, testing/bats/psql-commands.bats, testing/go/pgcatalog_test.go
Moves over already defined schemas from [this PR](https://github.com/dolthub/doltgresql/pull/190).
Includes pg_am, pg_attribute, pg_class, pg_constraint, pg_event_trigger, pg_index, pg_namespace, pg_proc, pg_trigger, and pg_type
=> Add schemas with empty row iters for some `pg_catalog` tables

server/analyzer/indexes.go, server/analyzer/init.go, server/ast/expr.go, server/expression/binary_operator.go, server/expression/explicit_cast.go
Companion PR: https://github.com/dolthub/go-mysql-server/pull/2566
This enables partial index support for a constrained set of comparisons.
=> Enable partial index support

go.mod, go.sum, server/analyzer/type_sanitizer.go, server/expression/in_tuple.go, testing/go/smoke_test.go
Companion PR: https://github.com/dolthub/dolt/pull/8073
Created indexes in Doltgres were not actually added to the table, which was fixed in the above PR. In addition, `IN` was corrected to use comparison functions (`IN` predates their creation) and `SUM` was excluded from the list of cast functions since GMS does not search children when looking for certain aggregate functions.
In addition, `IN` was overhauled so that comparison functions are resolved once. More details may be found in the accompanying comments.
=> Fixed some index issues and IN comparisons

go.mod, go.sum, testing/go/smoke_test.go
* Companion PR: https://github.com/dolthub/dolt/pull/8081
The companion PR fixes two issues regarding the creation of the secondary index map, which resulted in the now-unskipped tests either panicking or returning incorrect results. With the merger of the aforementioned PR, both of these issues will be fixed.
=> Fixed secondary indexing

server/analyzer/indexes.go
`select_random_points` is performing slower than expected, and this is due to `IN` not using indexes. This just adds `IN` to the index logic, so that `select_random_points` will now actually use indexes. This logic does not properly reflect how PostgreSQL should really behave, but currently _none_ of the index logic behaves properly due to GMS requiring exact type matches, rather than relying on comparison operators, so there's no additional harm in adding this.
No new tests are added, as we already have pre-existing tests for `IN` using indexes. They just didn't actually use the index, but still returned the correct result, and now they're using the index as well.
=> Added IN to indexes

server/functions/init.go, server/functions/version.go, testing/go/functions_test.go
Relies on GMS PR: https://github.com/dolthub/go-mysql-server/pull/2588
=> Fix `version` function so that it returns Postgres version

server/functions/col_description.go, server/functions/init.go, server/functions/obj_description.go, server/functions/shobj_description.go, testing/go/functions_test.go, testing/go/information_schema_test.go
These will return an empty string until we support comments
=> Add comment information system functions

server/functions/format_type.go, server/functions/framework/compiled_function.go
We had a workaround to allow function resolution to handle `NULL` expressions (`NULL` values worked fine since they still resolved to a non-`NULL` type). This adds the necessary logic so that we no longer need the workaround, and the `NULL` expression is properly resolved.
=> Fixed function resolution for NULLs

server/expression/assignment_cast.go, server/functions/framework/cast.go, server/types/internal_char.go, testing/go/operators_test.go, testing/go/types_test.go
Three main things here:
* I accidentally got the automatic string casting backwards. Automatic assignment should be _to strings_, and automatic explicit should be _from_ strings.
* I think I got these backward because string literals should technically have the `unknown` type, which can be interpreted as any type using the `IoInput` functions. However, I assign them the `text` type, which is incorrect, and caused a difference in behavior where reversing the automatic casts caused the correct observable behavior for the written tests. Of course, more tests showed the flaws.
* My assumptions with the operators was still partially correct. It's automatically casting `"char"` to `text`, and then using the `text` operators. The tests all passed because they're valid for both `"char"` and …
=> [no-release-notes] Fixed literal casting, added more "char" tests

server/ast/discard.go, server/connection_handler.go, server/node/discard.go, testing/generation/command_docs/output/discard_test.go, testing/go/session_test.go
Fixes https://github.com/dolthub/doltgresql/issues/591
=> Implemented DISCARD

server/ast/expr.go, server/expression/in_subquery.go, testing/go/enginetest/doltgres_engine_test.go, testing/go/expressions_test.go
Tuples won't work until we have a doltgres tuple type, but should work for everything else.
New expression type is a combination of InTuple from Doltgres and InSubquery from GMS. GMS code couldn't really be reused usefully.
=> Support for IN with a subquery

server/functions/ascii.go, server/functions/bit_length.go, server/functions/btrim.go, server/functions/char_length.go, server/functions/chr.go, server/functions/initcap.go, server/functions/left.go, server/functions/length.go, server/functions/lower.go, server/functions/lpad.go, server/functions/ltrim.go, server/functions/md5.go, server/functions/octet_length.go, server/functions/repeat.go, server/functions/replace.go, server/functions/reverse.go, server/functions/right.go, server/functions/rpad.go, server/functions/rtrim.go, server/functions/split_part.go, server/functions/substr.go, server/functions/to_hex.go, server/functions/upper.go, server/tables/pgcatalog/pg_am.go, server/tables/pgcatalog/pg_class.go, testing/go/functions_test.go, testing/go/pgcatalog_test.go
This allows displaying index information on TablePlus
=> add Postgres default access methods in `pg_am` table

postgres/messages/parameter_description.go, postgres/messages/parse.go, postgres/messages/row_description.go, server/connection_handler.go, server/converted_query.go
Note: the prepared tests don't utilize this field in the `Parse` message, so it needs to extract the binding value types from analyzed plan of the query.
=> use ParameterObjectIDs in Parse message for binding variable types

server/authentication_scram.go, server/connection_handler.go
This implements the initial portion of the authentication protocol.
Postgres Reference Documentation:
* https://www.postgresql.org/docs/15/protocol-flow.html
* https://www.postgresql.org/docs/15/sasl-authentication.html
Primarily, this implements `SASL SCRAM-SHA-256`, which _appears_ to be the primary form of authentication used in modern Postgres. It has been built by following the RFC specification:
* https://datatracker.ietf.org/doc/html/rfc5802
There are no tests since the implementation is incomplete. It cannot truly be tested until we have passwords and such that it can verify against (as the results must be sent back to the client for verification, so it can't be faked), however I have tested it up through what has been written, and what exists works as it should.
Surprisingly, …
=> Initial Authentication Protocol

server/index/table.go, server/index/writable_table.go, testing/go/framework.go, testing/go/smoke_test.go
Fixes:
* https://github.com/dolthub/doltgresql/issues/730
For _some_ index joins, the analyzer will create a specific type of plan that creates MySQL ranges rather than Doltgres ranges. It appears as though there may be divergent branches for the join logic, so I attempted to look for the source of the divergence, however I came up short.
For now, rather than chasing this down and delaying a PR (since Tim needs this fixed asap), we can pass the lookup to the internal Dolt table. This will return incorrect results in some situations, but it won't panic for now, so I'll follow up with a better search through GMS at a later date to merge the index join paths.
=> Fixed panic for some index joins

server/connection_handler.go, testing/go/regression/tool/message_reader.go, testing/go/regression/tool/replay.go
Doltgres may occasionally send multiple `ReadyForQuery` messages rather than just one, which is an error. This changes the regression tool so that it now flushes after receiving `ReadyForQuery`, so that such errors do not cause big regression swings when they are fixed.
=> [no-release-notes] Flush messages in regression tool after ReadyForQuery

go.mod, go.sum, server/authentication_scram.go, server/users/mock_database.go, server/users/rfc5802/doc.go, server/users/rfc5802/functions.go, testing/go/framework.go
For the most part, this implements the following portions of [RFC 5802](https://datatracker.ietf.org/doc/html/rfc5802):
* [Section 2.2](https://datatracker.ietf.org/doc/html/rfc5802#section-2.2)
* [Section 3](https://datatracker.ietf.org/doc/html/rfc5802#section-3)
* Validation portion of [Section 5](https://datatracker.ietf.org/doc/html/rfc5802#section-5)
This also bases the stored data from:
* https://www.postgresql.org/docs/15/catalog-pg-authid.html
This PR finally lets the server do the full authentication routine with the client. For now, I've created a mock database full of mock users, which are actually being tested by all of our engine tests since we do supply a username and password when creating and setting up the server. The `pgx` library is handling the client-side …
=> Added RFC5802 for user client authentication

postgres/parser/sem/tree/pretty.go
The intention here should be to initialize a slice with a capacity of length rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW
=> fix: fix slice init length

server/functions/nextval.go, server/functions/setval.go, server/node/copy_from.go, testing/bats/dataloading.bats, testing/bats/dataloading/tab-load-with-quoted-column-names.sql, testing/go/sequences_test.go
While investigating https://github.com/dolthub/doltgresql/issues/843, several statements were failing due to double-quoted identifiers. This PR fixes `COPY` statements and use of `nextval()` and `setval()` to properly parse double-quoted identifiers.
=> Bug fixes for double-quoted relation names

.github/workflows/label-customer-issues.yaml
Adds a GitHub Actions workflow to label PRs from outside the team with the "contribution" label. This is the same workflow we use for dolt/go-mysql-server/etc.
=> Label contribution PRs

server/functions/init.go, server/functions/set_config.go, testing/generation/function_coverage/output/set_config_test.go
Adds support for [the `set_config()` function](https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-SET). 
**Example Usage:**
```sql
SELECT set_config('mynamespace.foo', 'bar', false);
set_config 
------------
bar
SELECT current_setting('mynamespace.foo');
current_setting 
-----------------
bar
```
Fixes: https://github.com/dolthub/doltgresql/issues/852
=> Function: `set_config()`

core/rootvalue.go, core/typecollection/merge.go, core/typecollection/serialization.go, core/typecollection/typecollection.go, server/ast/drop_domain.go, server/node/create_domain.go, server/node/drop_domain.go, server/types/domain.go, server/types/globals.go, server/types/interface.go, testing/generation/command_docs/output/drop_domain_test.go, testing/go/domain_test.go
Added:
- merge functionality for domain types
- check for domain usage in tables for dropping domain
TODO:
- creating domain type creates instance of array type of this domain type
- unique OID generated for each domain created
- add domains to pg_type
- `ALTER TABLE` (e.g.: modify existing column to domain type column)
- use domain type as underlying type to another domain
=> drop domain support

server/functions/current_schema.go, server/functions/current_schemas.go, server/functions/nextval.go, server/settings/current_schemas.go, server/settings/doc.go, server/types/oid/regclass.go, server/types/text.go, testing/go/functions_test.go, testing/go/sequences_test.go, testing/go/types_test.go
Allows the `nextval()` function to take a `regclass` parameter. Also changes the output function of `regclass` so that the returned relation name is schema-qualified if the schema is not on `search_path`. 
This change also moves the `GetCurrentSchemas()` function into a new `settings` package to break a package import cycle. The new `settings` package is intended for low-level functions that access settings, without dependencies on other packages. 
Fixes: https://github.com/dolthub/doltgresql/issues/850
=> Allow `nextval()` to take a regclass instance

server/ast/create_table.go
We parse, but ignore, `PARTITION BY` clauses in `CREATE TABLE` statements in gms, so do the same thing here.
Docs noting this here: https://github.com/dolthub/docs/pull/2392
=> partitions are no-ops

server/ast/create_table.go
Catch `PARTITION OF` statements and return error instead of panicking.
=> throw unsupported error for `PARTITION OF` statements

core/context.go, server/tables/pgcatalog/pg_attrdef.go, server/tables/pgcatalog/pg_attribute.go, server/tables/pgcatalog/pg_catalog_cache.go, server/tables/pgcatalog/pg_class.go, server/tables/pgcatalog/pg_constraint.go, server/tables/pgcatalog/pg_index.go, server/tables/pgcatalog/pg_indexes.go, server/tables/pgcatalog/pg_namespace.go, server/tables/pgcatalog/pg_sequence.go, server/tables/pgcatalog/pg_tables.go, server/tables/pgcatalog/pg_type.go, server/tables/pgcatalog/pg_views.go, server/types/oid/iterate.go, testing/go/pgcatalog_test.go
While investigating performance on some skipped tests for `pg_catalog` tables, I found a few areas to optimize around how we deal with OIDs. The biggest source of latency I found was that `pg_catalog` tables must iterate through every object in a database (e.g. schemas, tables, indexes, types) to generate OIDs and create the rows for each `pg_catalog` table. When multiple `pg_catalog` tables are joined together, this starts to consume a significant amount of time, with some queries triggering this database iteration process hundreds of thousands of times. 
This change creates a new cache in the session object that stores the data for `pg_catalog` tables so that it can be reused within the same query. The effect is that several queries that timed out before will now complete. Some of these …
=> Add caching for `pg_catalog` tables

go.mod, go.sum, server/tables/dtables/ignore.go, server/tables/dtables/init.go, server/tables/dtables/rebase.go, testing/go/dolt_tables_test.go
Dolt PR: https://github.com/dolthub/dolt/pull/8578/files
=> Tests and fixes for dolt_rebase and dolt_ignore

server/functions/init.go, server/functions/pg_get_serial_sequence.go, testing/go/functions_test.go
Adds support for the `pg_get_serial_sequence(text,text)` function, which returns the sequence owned by a column. 
Example usage:
```
create table t1 (id SERIAL PRIMARY KEY);
SELECT pg_get_serial_sequence('t1', 'id');
```
=> Add support for `pg_get_serial_sequence(text,text)`

server/server.go
Account for interface change in Dolt: https://github.com/dolthub/dolt/pull/8708
=> CliContext interface update. NoOp

server/ast/alter_table.go, server/ast/no_op.go, server/node/no_op.go, testing/go/alter_table_test.go
Used for OWNER ddl statements for now, and will extend to VACUUM next.
=> Implemented a no-op node for statements that can be safely ignored

server/analyzer/init.go, server/analyzer/validate_column_defaults.go, server/doltgres_handler.go, server/functions/gen_random_uuid.go, server/functions/init.go, server/node/create_table.go, testing/go/alter_table_test.go, testing/go/subqueries_test.go
Removed the GMS validateColumnDefaults rule in favor of our own, and also made it run on CreateTable statements (it wasn't before due to an oversight in a type assertion).
Also implemented the gen_random_uuid function.
=> bug fix for column defaults with function values

server/functions/framework/interpreter_logic.go, server/functions/framework/interpreter_operation.go, server/functions/framework/interpreter_stack.go, server/functions/interpreted_examples.go, testing/go/create_function_test.go
Adds support for the execution logic for the `ALIAS` statement in user defined functions.
=> PL/pgSQL: Add support for the `ALIAS` statement

scripts/build_binaries.sh
Pulling in the `pg_query_go` library added a CGO dependency, and the Windows build requires the stack smash protection library to be linked in. Unix builds do not, because it's built into Clang.
=> Fix SSP linker errors for Windows build

server/plpgsql/interpreter_logic.go, testing/go/create_function_test.go
Simple bug, but was difficult to spot. Some statements work _without_ needing to advance the returned `RowIter`, while others _require_ advancing it. I changed it so that we're always advancing the iterator. I also unskipped the skipped tests, and removed the temporary one since the original now works.
=> Fixed CREATE FUNCTION not executing some statements

testing/go/create_function_test.go
We get support for `NULL` statements from `pg_query_go` since it automatically filters them out. This change adds a test of their usage.
=> `NULL` support in PL/pgSQL

server/plpgsql/interpreter_logic.go, server/plpgsql/interpreter_operation.go, server/plpgsql/interpreter_stack.go, server/plpgsql/json.go, server/plpgsql/json_convert.go, server/plpgsql/parse.go, server/plpgsql/reconcile_labels.go, server/plpgsql/statements.go, testing/go/create_function_test.go
This adds the rest of the "non-FOR" loops, along with loop control flow and labels. I also noticed that we weren't using `OperationSizeForStatements`, which will properly calculate offsets for the `Goto` operations, so I fixed that. Just so happened that our tests weren't running into the issue.
=> Added loop structures and label support

core/context.go, core/functions/function.go, core/functions/merge.go, core/functions/serialization.go, core/init.go, core/rootvalue.go, core/storage.go, flatbuffers/gen/serial/rootvalue.go, flatbuffers/serial/rootvalue.fbs, server/ast/create_function.go, server/functions/framework/catalog.go, server/functions/framework/provider.go, server/node/create_function.go, server/plpgsql/interpreter_logic.go, testing/go/create_function_test.go, utils/reader.go, utils/writer.go
This changes created functions such that they're now written to the root value, instead of being added to the global function list. This also supports overloading created functions.
=> Changed created functions to persist on the root

server/analyzer/convert_drop_primary_key_constraint.go, server/analyzer/generate_fk_name.go, server/analyzer/init.go, server/ast/table_def.go, server/tables/pgcatalog/pg_constraint.go, testing/go/create_table_test.go, testing/go/foreign_keys_test.go, testing/go/functions_test.go, testing/go/pgcatalog_test.go, testing/postgres-client-tests/node/workbenchTests/diffs.js, testing/postgres-client-tests/node/workbenchTests/table.js
Addresses several issues around primary key and foreign key naming:
* ability to drop a primary key using its default postgres name
* declaring a foreign key reference inline in a column definition
* default foreign key names now match postgres
* fix for `pg_constaints` incorrectly listing non-unique and non-pk indexes 
Note that the regressions listed are all related to now honoring foreign key references inline in a column definition. Before, these statements were executing, but the FK reference was ignored. Now that we honor the FK reference, several tests broke for the following reasons:
* [`DROP TABLE` doesn't automatically sort multiple tables by FK dependencies](https://github.com/dolthub/doltgresql/issues/1272)
* A required index didn't exist or wasn't automatically created 
* FKs …
=> Bug fixes for primary and foreign key naming

server/analyzer/convert_drop_primary_key_constraint.go, server/analyzer/generate_fk_name.go, testing/go/alter_table_test.go, testing/go/foreign_keys_test.go
Matches Postgres' behavior where default foreign key name collisions are resolved by adding an integer suffix to the name to make it unique. 
Also includes a bug fix for setting the target schema when dropping a primary key. 
Fixes a couple more issues with supporting DoltHub's schema in Doltgres.
=> Avoid name collisions for generated FK names

server/ast/create_database.go, testing/go/create_database_test.go
Fixes https://github.com/dolthub/doltgresql/issues/1261
=> Support `ENCODING` in `CREATE DATABASE`

testing/go/alter_table_test.go
Altering a column with an existing column default expression was triggering a panic in Doltgres, because Doltgres' `TypeSanitizer` was finding an `UnresolvedColumnDefault` instance in the `plan.ModifyColumn` instances's `column` field. 
This is not an issue from Dolt or GMS, because they don't support MySQL's syntax to alter a single component of an existing column, without requiring its full column definition to be respecified. (And also because they don't use Doltgres' `TypeSanitizer`.)
Depends on https://github.com/dolthub/dolt/pull/8994
Depends on https://github.com/dolthub/go-mysql-server/pull/2895
=> Add tests for `ALTER COLUMN` to assert that column default expressions are resolved

server/ast/alter_table.go, testing/go/alter_table_test.go
The regressions listed below are caused by us now honoring the inline check constraint definition, instead of ignoring them. GMS doesn't update the scope with the new column, so check constraints that use the column at the same time as adding it don't work properly. MySQL also supports this behavior, but we don't support it in GMS yet, so the fix for these regressions will be in GMS.
=> Allow `ALTER TABLE ADD COLUMN` to specify an inline FK constraint

postgres/parser/pgdate/field_extract.go, postgres/parser/pgdate/parsing_test.go, testing/go/insert_test.go
=> Bug fix: parsing iso8601 date strings

server/functions/advisory_locks.go, server/functions/init.go, testing/go/lock_test.go
Adds support for three [Postgres advisory lock functions](https://www.postgresql.org/docs/9.1/functions-admin.html#FUNCTIONS-ADVISORY-LOCKS):
* `pg_try_advisory_lock()`
* `pg_advisory_lock()`
* `pg_advisory_unlock()`
A couple TODOs call out follow-ups to make `LockSubsystem` work better with Postgres' behavior, such as supporting reentrant locking. 
Fixes: https://github.com/dolthub/doltgresql/issues/1262
=> Initial support for advisory lock functions

server/connection_handler.go, testing/go/binding_test.go
When specifying parameters for a prepared query, callers can specify OID zero to instruct the server to infer the type. Doltgres was error'ing out in this case, because it couldn't find a valid OID registered for zero. This changes Doltgres to infer types when the specified parameter OIDs contains a zero. 
Found while testing a basic Rails app with Doltgres.
=> Infer types when clients specify a bind argument with OID zero

server/ast/alter_table.go, testing/go/alter_table_test.go
We were previously modeling an inline constraint definition as a separate DDL command. This changes it to be consistent with how GMS and Dolt works, by using a single DDL command, and setting the constraint action.
=> Changing how a constraint addition is structured, to match what Dolt/GMS does

go.mod, go.sum
v6.1.0 includes [a fix for building on MacOS 15.4](https://github.com/pganalyze/pg_query_go/issues/132)
=> Upgrade pganalyze/pg_query_go to v6.1.0

postgres/parser/parser/sql.y, server/analyzer/apply_analyze_all_tables.go, server/analyzer/init.go, server/ast/analyze.go, testing/generation/command_docs/output/analyze_test.go, testing/go/stats_test.go
When Postgres processes an `ANALYZE;` statement without any tables explicitly specified, it analyzes all tables. 
[Postgres docs](https://www.postgresql.org/docs/current/sql-analyze.html)
=> Add support for `ANALYZE;` without any tables specified

server/config/parameters_list.go, testing/go/parameters_test.go
[Postgres docs](https://www.postgresql.org/docs/11/runtime-config-compatible.html#GUC-DEFAULT-WITH-OIDS)
A few sample Postgres dumps set `default_with_oids`. This change allows them to set the parameter without triggering an error. Note that Doltgres does not support creating tables with OID columns, even if this parameter is set to true.
=> Add support for `default_with_oids`

server/functions/current_setting.go, testing/go/dolt_functions_test.go, testing/go/prepared_statement_test.go, testing/go/set_test.go
For https://github.com/dolthub/doltgresql/issues/1366
=> Add skipped tests for bugs hit from testing js frameworks, fix `current_setting`

server/ast/select.go, testing/go/dolt_tables_test.go, testing/go/insert_test.go
Fixes https://github.com/dolthub/doltgresql/issues/1394
=> Add skipped tests for insert...returning bugs, fix referenced schema in column name error

server/analyzer/type_sanitizer.go, server/expression/gms_cast.go, testing/go/dolt_tables_test.go
Fixes https://github.com/dolthub/doltgresql/issues/1405
This works by placing a typecast on unconverted dolt_ table fields so that they work in any expression that requires a doltgresType.
=> Bug fix for dolt_ tables with incompatible types

server/functions/framework/interpreted_function.go, server/plpgsql/interpreter_logic.go, testing/go/create_function_test.go
This implements the changes necessitated by the following fix:
* https://github.com/dolthub/go-mysql-server/pull/2949
We had a bug where calls to any DML statements that included an interpreted function would remove the DML's ability to actually affect the data. The GMS PR implements the core fix, and this PR implements the companion changes.
=> Fixed interpretation calls within DML

go.mod, go.sum
=> [auto-bump] [no-release-notes] dependency by zachmu

server/ast/alter_table.go, server/ast/column_table_def.go, server/ast/create_domain.go, server/ast/create_type.go, server/ast/expr.go, server/ast/resolvable_type_reference.go, server/compare/utils.go, server/expression/in_tuple.go, server/expression/record.go, server/functions/binary/equal.go, server/functions/binary/greater.go, server/functions/binary/greater_equal.go, server/functions/binary/less.go, server/functions/binary/less_equal.go, server/functions/binary/not_equal.go, server/functions/record.go, server/types/record.go, server/types/type.go, server/types/utils.go, testing/go/record_test.go
Initial support for the `ROW()` constructor expression, which creates anonymous records. 
This PR adds support for basic uses of the `ROW()` constructor, such as creating records from groups of expressions, selecting records, comparing records, and using records in `WHERE` clauses. There are still several `record` features that don't work yet, such as using a table alias with the `ROW()` constructor. 
Fixes: https://github.com/dolthub/doltgresql/issues/1425
Depends on: https://github.com/dolthub/go-mysql-server/pull/2982
=> Add `ROW()` record constructor support

testing/go/enginetest/doltgres_engine_test.go
Fixes dolthub/dolt#483
Add skip for test since `doltgres` harness does not create remote dir with `h.UseLocalFileSystem()`
=> Fix dolthub/dolt#483 - add skip for remote tracking branch and table same name test

scripts/build_binaries.sh
Also picks up newer versions of our crosstools toolchain and sets the platform_version metadata in the MacOS builds so that they will be more compatible with App Store release in the future if the Workbench ever supports Doltgres.
=> scripts/build_binaries.sh: Windows builds: statically link libssp so that doltgres.exe does not have a dependency on MinGW at runtime.

core/extensions/pg_extension/library/build_definitions.ps1
This extends the definitions build script to search for GCC and Clang too. These were all tested and confirmed to work locally.
=> Added GCC and Clang building

server/config/parameters.go
Erroring out is preventing gms from setting system variables when server starts (dolthub/go-mysql-server#3005) since [AssignValues calls InitValue with global set to true](https://github.com/dolthub/go-mysql-server/blob/main/sql/variables/system_variables.go#L81).
=> Remove error out for global parameters

postgres/parser/parser/sql.y
Removes two duplicate type definitions. Original customer report also mentioned unused tokens, although those have been left in, since they are valid Postgres tokens and many will likely be used as we continue extending Doltgres support. 
Related to: https://github.com/dolthub/doltgresql/issues/1592
=> Remove duplicate type definitions

testing/PostgresDockerfile, testing/go/enginetest/query_converter_test.go
Fixes dolthub/doltgresql#1708
Query converter was panicking with "unhandled type: sqlparser.BoolVal" when encountering boolean literals like FALSE in CREATE TABLE statements. This was blocking UNION column mapping tests from dolthub/dolt#9628. Postgres CI docker container is also end of life, switched next LTS ver of Ubuntu 22.04.
=> dolthub/doltgresql#1708 - Fix query converter crash on boolean literals

postgres/parser/parser/sql.y, postgres/parser/sem/tree/pretty.go, postgres/parser/sem/tree/select.go, testing/go/import_dumps_test.go, testing/go/smoke_test.go
Some dumps include columns that are named `"index"`, which is forbidden in CockroachDB. Our parser was initially based on an open-licensed version of CockroachDB's parser (https://github.com/dolthub/doltgresql/pull/19#issuecomment-1761392474), and we therefore inherited some of the restrictions that CockroachDB has. We want our customers to be able to use standard Postgres dumps, so this removes the CockroachDB extensions and restores the functionality expected of Postgres users. We didn't implement functionality for the extensions anyway, so this should be a harmless removal.
For reference, this is the page discussing the extensions:
https://www.cockroachlabs.com/docs/stable/order-by
=> Fixed INDEX reservation
